name: fullstack-challenge
services:
    app:
        build:
            context: ./docker
        container_name: app
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
    mysql:
        image: mysql:8
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:7
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    supervisor:
        build: 
            context: ./docker
            dockerfile: supervisor.dockerfile
        container_name: supervisor
        volumes:
            - .:/var/www/html
            
volumes:
    mysql_data:
    redis_data:
